// Replace with fonts in assignment description
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // change to title of the app in the project description
  title: {
    default: "RTS test-opgave",
    template: "%s | RTS test-opgave",
  },
  // change description to match the project
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      // change to the language of the app in the project description
      lang="en" 
      className={`${geistSans.variable} ${geistMono.variable}`
    }>
      <body>
        {/* Add header and footer in this layout */}
        {children}
      </body>
    </html>
  );
}
